# Generated by Django 3.0.1 on 2023-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='icon',
            field=models.CharField(default='Pinterest.png', max_length=255),
        ),
    ]
